// Shared language data for both client and server
// This file has NO "use client" directive so it can be imported in API routes

export interface Language {
  value: string
  label: string
  region: string
  nativeName?: string
}

// Comprehensive language list with native languages from all continents
export const languages: Language[] = [
  // ==================== AFRICAN LANGUAGES ====================
  // West Africa
  { value: "yoruba", label: "Yoruba", region: "Africa", nativeName: "Èdè Yorùbá" },
  { value: "igbo", label: "Igbo", region: "Africa", nativeName: "Asụsụ Igbo" },
  { value: "hausa", label: "Hausa", region: "Africa", nativeName: "Harshen Hausa" },
  { value: "akan", label: "Akan (Twi)", region: "Africa", nativeName: "Akan" },
  { value: "ewe", label: "Ewe", region: "Africa", nativeName: "Eʋegbe" },
  { value: "ga", label: "Ga", region: "Africa", nativeName: "Gã" },
  { value: "wolof", label: "Wolof", region: "Africa", nativeName: "Wolof" },
  { value: "fulani", label: "Fulani (Fula)", region: "Africa", nativeName: "Fulfulde" },
  { value: "bambara", label: "Bambara", region: "Africa", nativeName: "Bamanankan" },
  { value: "mandinka", label: "Mandinka", region: "Africa", nativeName: "Mandinka" },
  { value: "soninke", label: "Soninke", region: "Africa", nativeName: "Sooninkanxanne" },
  { value: "serer", label: "Serer", region: "Africa", nativeName: "Seereer" },
  { value: "temne", label: "Temne", region: "Africa", nativeName: "Temne" },
  { value: "krio", label: "Krio", region: "Africa", nativeName: "Krio" },
  { value: "moore", label: "Mossi (Mooré)", region: "Africa", nativeName: "Mooré" },
  { value: "fon", label: "Fon", region: "Africa", nativeName: "Fɔ̀ngbè" },
  { value: "edo", label: "Edo (Bini)", region: "Africa", nativeName: "Ẹ̀dó" },
  { value: "ibibio", label: "Ibibio", region: "Africa", nativeName: "Ibibio" },
  { value: "efik", label: "Efik", region: "Africa", nativeName: "Efik" },
  { value: "tiv", label: "Tiv", region: "Africa", nativeName: "Tiv" },
  { value: "nupe", label: "Nupe", region: "Africa", nativeName: "Nupe" },
  { value: "kanuri", label: "Kanuri", region: "Africa", nativeName: "Kanuri" },
  
  // East Africa
  { value: "swahili", label: "Swahili", region: "Africa", nativeName: "Kiswahili" },
  { value: "amharic", label: "Amharic", region: "Africa", nativeName: "አማርኛ" },
  { value: "oromo", label: "Oromo", region: "Africa", nativeName: "Afaan Oromoo" },
  { value: "tigrinya", label: "Tigrinya", region: "Africa", nativeName: "ትግርኛ" },
  { value: "somali", label: "Somali", region: "Africa", nativeName: "Soomaali" },
  { value: "luganda", label: "Luganda", region: "Africa", nativeName: "Oluganda" },
  { value: "kikuyu", label: "Kikuyu", region: "Africa", nativeName: "Gĩkũyũ" },
  { value: "luo", label: "Luo (Dholuo)", region: "Africa", nativeName: "Dholuo" },
  { value: "kamba", label: "Kamba", region: "Africa", nativeName: "Kikamba" },
  { value: "luhya", label: "Luhya", region: "Africa", nativeName: "Oluluyia" },
  { value: "kalenjin", label: "Kalenjin", region: "Africa", nativeName: "Kalenjin" },
  { value: "maasai", label: "Maasai", region: "Africa", nativeName: "ɔl Maa" },
  { value: "kinyarwanda", label: "Kinyarwanda", region: "Africa", nativeName: "Ikinyarwanda" },
  { value: "kirundi", label: "Kirundi", region: "Africa", nativeName: "Ikirundi" },
  { value: "gikuyu", label: "Gikuyu", region: "Africa", nativeName: "Gĩkũyũ" },
  
  // Southern Africa
  { value: "zulu", label: "Zulu", region: "Africa", nativeName: "isiZulu" },
  { value: "xhosa", label: "Xhosa", region: "Africa", nativeName: "isiXhosa" },
  { value: "afrikaans", label: "Afrikaans", region: "Africa", nativeName: "Afrikaans" },
  { value: "sotho", label: "Sotho", region: "Africa", nativeName: "Sesotho" },
  { value: "tswana", label: "Tswana", region: "Africa", nativeName: "Setswana" },
  { value: "shona", label: "Shona", region: "Africa", nativeName: "chiShona" },
  { value: "ndebele", label: "Ndebele", region: "Africa", nativeName: "isiNdebele" },
  { value: "venda", label: "Venda", region: "Africa", nativeName: "Tshivenḓa" },
  { value: "tsonga", label: "Tsonga", region: "Africa", nativeName: "Xitsonga" },
  { value: "swazi", label: "Swazi", region: "Africa", nativeName: "siSwati" },
  { value: "nyanja", label: "Nyanja (Chewa)", region: "Africa", nativeName: "Chichewa" },
  { value: "tumbuka", label: "Tumbuka", region: "Africa", nativeName: "chiTumbuka" },
  { value: "bemba", label: "Bemba", region: "Africa", nativeName: "ChiBemba" },
  { value: "lozi", label: "Lozi", region: "Africa", nativeName: "siLozi" },
  { value: "herero", label: "Herero", region: "Africa", nativeName: "Otjiherero" },
  { value: "ovambo", label: "Ovambo", region: "Africa", nativeName: "Oshiwambo" },
  { value: "san", label: "San (Khoisan)", region: "Africa", nativeName: "Khoisan" },
  
  // Central Africa
  { value: "kongo", label: "Kongo", region: "Africa", nativeName: "Kikongo" },
  { value: "lingala", label: "Lingala", region: "Africa", nativeName: "Lingála" },
  { value: "tshiluba", label: "Tshiluba", region: "Africa", nativeName: "Tshiluba" },
  { value: "sango", label: "Sango", region: "Africa", nativeName: "Sängö" },
  { value: "fang", label: "Fang", region: "Africa", nativeName: "Fang" },
  { value: "bulu", label: "Bulu", region: "Africa", nativeName: "Bulu" },
  { value: "ewondo", label: "Ewondo", region: "Africa", nativeName: "Ewondo" },
  { value: "douala", label: "Douala", region: "Africa", nativeName: "Duala" },
  
  // North Africa
  { value: "arabic", label: "Arabic", region: "Africa", nativeName: "العربية" },
  { value: "berber", label: "Berber (Tamazight)", region: "Africa", nativeName: "ⵜⴰⵎⴰⵣⵉⵖⵜ" },
  { value: "kabyle", label: "Kabyle", region: "Africa", nativeName: "Taqbaylit" },
  { value: "tuareg", label: "Tuareg (Tamashek)", region: "Africa", nativeName: "Tamashek" },
  { value: "hassaniya", label: "Hassaniya Arabic", region: "Africa", nativeName: "حسانية" },
  
  // Island
  { value: "malagasy", label: "Malagasy", region: "Africa", nativeName: "Malagasy" },
  
  // ==================== ASIAN LANGUAGES ====================
  // East Asia
  { value: "mandarin", label: "Mandarin Chinese", region: "Asia", nativeName: "普通话" },
  { value: "cantonese", label: "Cantonese", region: "Asia", nativeName: "粵語" },
  { value: "korean", label: "Korean", region: "Asia", nativeName: "한국어" },
  { value: "japanese", label: "Japanese", region: "Asia", nativeName: "日本語" },
  
  // Southeast Asia
  { value: "thai", label: "Thai", region: "Asia", nativeName: "ไทย" },
  { value: "vietnamese", label: "Vietnamese", region: "Asia", nativeName: "Tiếng Việt" },
  { value: "tagalog", label: "Tagalog", region: "Asia", nativeName: "Tagalog" },
  { value: "burmese", label: "Burmese", region: "Asia", nativeName: "ဗမာ" },
  { value: "khmer", label: "Khmer", region: "Asia", nativeName: "ខ្មែរ" },
  { value: "lao", label: "Lao", region: "Asia", nativeName: "ລາວ" },
  { value: "malay", label: "Malay", region: "Asia", nativeName: "Bahasa Melayu" },
  { value: "indonesian", label: "Indonesian", region: "Asia", nativeName: "Bahasa Indonesia" },
  
  // South Asia
  { value: "hindi", label: "Hindi", region: "Asia", nativeName: "हिंदी" },
  { value: "bengali", label: "Bengali", region: "Asia", nativeName: "বাংলা" },
  { value: "punjabi", label: "Punjabi", region: "Asia", nativeName: "ਪੰਜਾਬੀ" },
  { value: "marathi", label: "Marathi", region: "Asia", nativeName: "मराठी" },
  { value: "gujarati", label: "Gujarati", region: "Asia", nativeName: "ગુજરાતી" },
  { value: "tamil", label: "Tamil", region: "Asia", nativeName: "தமிழ்" },
  { value: "telugu", label: "Telugu", region: "Asia", nativeName: "తెలుగు" },
  { value: "kannada", label: "Kannada", region: "Asia", nativeName: "ಕನ್ನಡ" },
  { value: "malayalam", label: "Malayalam", region: "Asia", nativeName: "മലയാളം" },
  { value: "odia", label: "Odia (Oriya)", region: "Asia", nativeName: "ଓଡିଆ" },
  { value: "urdu", label: "Urdu", region: "Asia", nativeName: "اردو" },
  { value: "sinhalese", label: "Sinhalese", region: "Asia", nativeName: "සිංහල" },
  
  // Central & West Asia
  { value: "persian", label: "Persian (Farsi)", region: "Asia", nativeName: "فارسی" },
  { value: "turkish", label: "Turkish", region: "Asia", nativeName: "Türkçe" },
  { value: "kazakh", label: "Kazakh", region: "Asia", nativeName: "Қазақ" },
  { value: "uzbek", label: "Uzbek", region: "Asia", nativeName: "Ўзбек" },
  { value: "tajik", label: "Tajik", region: "Asia", nativeName: "Тоҷикӣ" },
  { value: "kyrgyz", label: "Kyrgyz", region: "Asia", nativeName: "Кыргызча" },
  { value: "mongol", label: "Mongolian", region: "Asia", nativeName: "Монгол" },
  
  // ==================== EUROPEAN LANGUAGES ====================
  { value: "english", label: "English", region: "Europe", nativeName: "English" },
  { value: "spanish", label: "Spanish", region: "Europe", nativeName: "Español" },
  { value: "french", label: "French", region: "Europe", nativeName: "Français" },
  { value: "german", label: "German", region: "Europe", nativeName: "Deutsch" },
  { value: "italian", label: "Italian", region: "Europe", nativeName: "Italiano" },
  { value: "portuguese", label: "Portuguese", region: "Europe", nativeName: "Português" },
  { value: "dutch", label: "Dutch", region: "Europe", nativeName: "Nederlands" },
  { value: "polish", label: "Polish", region: "Europe", nativeName: "Polski" },
  { value: "russian", label: "Russian", region: "Europe", nativeName: "Русский" },
  { value: "ukrainian", label: "Ukrainian", region: "Europe", nativeName: "Українська" },
  { value: "romanian", label: "Romanian", region: "Europe", nativeName: "Română" },
  { value: "czech", label: "Czech", region: "Europe", nativeName: "Čeština" },
  { value: "slovak", label: "Slovak", region: "Europe", nativeName: "Slovenčina" },
  { value: "hungarian", label: "Hungarian", region: "Europe", nativeName: "Magyar" },
  { value: "greek", label: "Greek", region: "Europe", nativeName: "Ελληνικά" },
  { value: "bulgarian", label: "Bulgarian", region: "Europe", nativeName: "Български" },
  { value: "serbian", label: "Serbian", region: "Europe", nativeName: "Српски" },
  { value: "croatian", label: "Croatian", region: "Europe", nativeName: "Hrvatski" },
  { value: "slovenian", label: "Slovenian", region: "Europe", nativeName: "Slovenščina" },
  { value: "finnish", label: "Finnish", region: "Europe", nativeName: "Suomi" },
  { value: "swedish", label: "Swedish", region: "Europe", nativeName: "Svenska" },
  { value: "norwegian", label: "Norwegian", region: "Europe", nativeName: "Norsk" },
  { value: "danish", label: "Danish", region: "Europe", nativeName: "Dansk" },
  { value: "icelandic", label: "Icelandic", region: "Europe", nativeName: "Íslenska" },
  { value: "irish", label: "Irish", region: "Europe", nativeName: "Gaeilge" },
  { value: "scottish", label: "Scottish Gaelic", region: "Europe", nativeName: "Gàidhlig" },
  { value: "welsh", label: "Welsh", region: "Europe", nativeName: "Cymraeg" },
  { value: "basque", label: "Basque", region: "Europe", nativeName: "Euskera" },
  { value: "catalan", label: "Catalan", region: "Europe", nativeName: "Català" },
  { value: "hindi", label: "Hindi", region: "Europe", nativeName: "हिंदी" },
  { value: "albanian", label: "Albanian", region: "Europe", nativeName: "Shqip" },
  { value: "lithuanian", label: "Lithuanian", region: "Europe", nativeName: "Lietuvių" },
  { value: "latvian", label: "Latvian", region: "Europe", nativeName: "Latviešu" },
  { value: "estonian", label: "Estonian", region: "Europe", nativeName: "Eesti" },
  { value: "maltese", label: "Maltese", region: "Europe", nativeName: "Malti" },
  { value: "luxembourgish", label: "Luxembourgish", region: "Europe", nativeName: "Lëtzebuergesch" },
  
  // ==================== AMERICAS LANGUAGES ====================
  // North America
  { value: "english-us", label: "English (US)", region: "Americas", nativeName: "English" },
  { value: "french-canadian", label: "French (Canadian)", region: "Americas", nativeName: "Français" },
  { value: "spanish-mexican", label: "Spanish (Mexican)", region: "Americas", nativeName: "Español" },
  
  // Central America & Caribbean
  { value: "spanish-castilian", label: "Spanish (Castilian)", region: "Americas", nativeName: "Español" },
  
  // South America
  { value: "portuguese-brazilian", label: "Portuguese (Brazilian)", region: "Americas", nativeName: "Português" },
  { value: "quechua", label: "Quechua", region: "Americas", nativeName: "Quechua" },
  { value: "aymara", label: "Aymara", region: "Americas", nativeName: "Aymara" },
  { value: "guarani", label: "Guarani", region: "Americas", nativeName: "Guaraní" },
  
  // Indigenous Languages of Americas
  { value: "navajo", label: "Navajo", region: "Americas", nativeName: "Diné Bizaad" },
  { value: "cherokee", label: "Cherokee", region: "Americas", nativeName: "ᏣᎳᎩ" },
  { value: "sioux", label: "Sioux (Lakota)", region: "Americas", nativeName: "Lakota" },
  
  // ==================== OCEANIA LANGUAGES ====================
  { value: "samoan", label: "Samoan", region: "Oceania", nativeName: "Samoa" },
  { value: "tongan", label: "Tongan", region: "Oceania", nativeName: "Tonga" },
  { value: "fijian", label: "Fijian", region: "Oceania", nativeName: "Vosa Vakaviti" },
  { value: "maori", label: "Te Reo Maori", region: "Oceania", nativeName: "Te Reo Maori" },
  { value: "hawaiian", label: "Hawaiian", region: "Oceania", nativeName: "ʻŌlelo Hawaiʻi" },
  { value: "paluan", label: "Palauan", region: "Oceania", nativeName: "Palauan" },
  { value: "chamorro", label: "Chamorro", region: "Oceania", nativeName: "Chamorro" },
  
  // ==================== MIDDLE EAST ====================
  { value: "hebrew", label: "Hebrew", region: "Middle East", nativeName: "עברית" },
  { value: "arabic-msa", label: "Arabic (Standard)", region: "Middle East", nativeName: "العربية" },
  { value: "kurdish", label: "Kurdish", region: "Middle East", nativeName: "کوردی" },
  { value: "pashto", label: "Pashto", region: "Middle East", nativeName: "پښتو" },
  { value: "dari", label: "Dari", region: "Middle East", nativeName: "دری" },
  { value: "armenian", label: "Armenian", region: "Middle East", nativeName: "Հայերեն" },
  { value: "georgian", label: "Georgian", region: "Middle East", nativeName: "ქართული" },
  { value: "azerbaijani", label: "Azerbaijani", region: "Middle East", nativeName: "Azərbaycanca" },
  
  // ==================== ADDITIONAL EUROPEAN LANGUAGES ====================
  { value: "galician", label: "Galician", region: "Europe", nativeName: "Galego" },
  { value: "occitan", label: "Occitan", region: "Europe", nativeName: "Occitan" },
  { value: "sardinian", label: "Sardinian", region: "Europe", nativeName: "Sardu" },
  { value: "sicilian", label: "Sicilian", region: "Europe", nativeName: "Sicilianu" },
  { value: "romansh", label: "Romansh", region: "Europe", nativeName: "Rumantsch" },
  { value: "corsican", label: "Corsican", region: "Europe", nativeName: "Corsu" },
  { value: "friulian", label: "Friulian", region: "Europe", nativeName: "Furlan" },
  { value: "ladin", label: "Ladin", region: "Europe", nativeName: "Ladin" },
  { value: "breton", label: "Breton", region: "Europe", nativeName: "Brezhoneg" },
  { value: "cornish", label: "Cornish", region: "Europe", nativeName: "Kernewek" },
  { value: "manx", label: "Manx", region: "Europe", nativeName: "Gaelg" },
  { value: "faroese", label: "Faroese", region: "Europe", nativeName: "Føroyskt" },
  { value: "yiddish", label: "Yiddish", region: "Europe", nativeName: "ייִדיש" },
  
  // ==================== ADDITIONAL ASIAN LANGUAGES ====================
  { value: "wu", label: "Wu Chinese", region: "Asia", nativeName: "吴语" },
  { value: "min", label: "Min Chinese", region: "Asia", nativeName: "閩南語" },
  { value: "hakka", label: "Hakka", region: "Asia", nativeName: "客家話" },
  { value: "gan", label: "Gan Chinese", region: "Asia", nativeName: "赣语" },
  { value: "xiang", label: "Xiang Chinese", region: "Asia", nativeName: "湘语" },
  { value: "taiwanese", label: "Taiwanese", region: "Asia", nativeName: "臺灣話" },
  { value: "tibetan", label: "Tibetan", region: "Asia", nativeName: "བོད་སྐད" },
  { value: "dzongkha", label: "Dzongkha", region: "Asia", nativeName: "ཇོང་ཁ" },
  { value: "javanese", label: "Javanese", region: "Asia", nativeName: "Basa Jawa" },
  { value: "sundanese", label: "Sundanese", region: "Asia", nativeName: "Basa Sunda" },
  { value: "balinese", label: "Balinese", region: "Asia", nativeName: "Basa Bali" },
  { value: "madurese", label: "Madurese", region: "Asia", nativeName: "Madhura" },
  { value: "minangkabau", label: "Minangkabau", region: "Asia", nativeName: "Baso Minangkabau" },
  { value: "acehnese", label: "Acehnese", region: "Asia", nativeName: "Bahsa Acèh" },
  { value: "banjarese", label: "Banjarese", region: "Asia", nativeName: "Bahasa Banjar" },
  { value: "buginese", label: "Buginese", region: "Asia", nativeName: "Basa Ugi" },
  { value: "makassarese", label: "Makassarese", region: "Asia", nativeName: "Basa Makassar" },
  { value: "iban", label: "Iban", region: "Asia", nativeName: "Iban" },
  { value: "tetun", label: "Tetun", region: "Asia", nativeName: "Tetun" },
  { value: "bikol", label: "Bikol", region: "Asia", nativeName: "Bikol" },
  { value: "waray", label: "Waray", region: "Asia", nativeName: "Winaray" },
  { value: "iloko", label: "Iloko", region: "Asia", nativeName: "Ilokano" },
  { value: "pangasinan", label: "Pangasinan", region: "Asia", nativeName: "Pangasinan" },
  { value: "kapampangan", label: "Kapampangan", region: "Asia", nativeName: "Kapampangan" },
  { value: "maguindanao", label: "Maguindanao", region: "Asia", nativeName: "Maguindanao" },
  { value: "maranao", label: "Maranao", region: "Asia", nativeName: "Maranao" },
  { value: "tausug", label: "Tausug", region: "Asia", nativeName: "Tausug" },
  { value: "ibanag", label: "Ibanag", region: "Asia", nativeName: "Ibanag" },
  { value: "garo", label: "Garo", region: "Asia", nativeName: "Garo" },
  { value: "khasi", label: "Khasi", region: "Asia", nativeName: "Khasi" },
  { value: "jaintia", label: "Jaintia", region: "Asia", nativeName: "Jaintia" },
  { value: "kuki", label: "Kuki", region: "Asia", nativeName: "Kuki" },
  { value: "naga", label: "Naga", region: "Asia", nativeName: "Naga" },
  { value: "munda", label: "Munda", region: "Asia", nativeName: "Mundari" },
  { value: "santa ali", label: "Santali", region: "Asia", nativeName: "Santal" },
  { value: "gond", label: "Gondi", region: "Asia", nativeName: "Gondi" },
  { value: "toda", label: "Toda", region: "Asia", nativeName: "Toda" },
  { value: "kota", label: "Kota", region: "Asia", nativeName: "Kota" },
  { value: "badaga", label: "Badaga", region: "Asia", nativeName: "Badaga" },
  { value: "irula", label: "Irula", region: "Asia", nativeName: "Irula" },
  { value: "kurumba", label: "Kurumba", region: "Asia", nativeName: "Kurumba" },
  { value: "savara", label: "Savara", region: "Asia", nativeName: "Savara" },
  { value: "yerukala", label: "Yerukala", region: "Asia", nativeName: "Yerukala" },
  { value: "adi", label: "Adi", region: "Asia", nativeName: "Adi" },
  { value: "war", label: "War", region: "Asia", nativeName: "War" },
  { value: "angami", label: "Angami Naga", region: "Asia", nativeName: "Angami" },
  { value: "ao", label: "Ao Naga", region: "Asia", nativeName: "Ao" },
  { value: "chang", label: "Chang Naga", region: "Asia", nativeName: "Chang" },
  { value: "konyak", label: "Konyak Naga", region: "Asia", nativeName: "Konyak" },
  { value: "lotha", label: "Lotha Naga", region: "Asia", nativeName: "Lotha" },
  { value: "pochuri", label: "Pochuri Naga", region: "Asia", nativeName: "Pochuri" },
  { value: "rengma", label: "Rengma Naga", region: "Asia", nativeName: "Rengma" },
  { value: "sema", label: "Sema Naga", region: "Asia", nativeName: "Sema" },
  { value: "tangsa", label: "Tangsa", region: "Asia", nativeName: "Tangsa" },
  { value: "yimchunger", label: "Yimchunger Naga", region: "Asia", nativeName: "Yimchunger" },
  
  // ==================== OCEANIA ADDITIONAL ====================
  { value: "tok_pisin", label: "Tok Pisin", region: "Oceania", nativeName: "Tok Pisin" },
  { value: "hiri_motu", label: "Hiri Motu", region: "Oceania", nativeName: "Hiri Motu" },
  { value: "bislama", label: "Bislama", region: "Oceania", nativeName: "Bislama" },
  { value: "marshallese", label: "Marshallese", region: "Oceania", nativeName: "Kajin M̧ajeļ" },
  { value: "yapese", label: "Yapese", region: "Oceania", nativeName: "Yap" },
  { value: "warlpiri", label: "Warlpiri", region: "Oceania", nativeName: "Warlpiri" },
  { value: "pitjantjatjara", label: "Pitjantjatjara", region: "Oceania", nativeName: "Pitjantjatjara" },
  { value: "arrernte", label: "Arrernte", region: "Oceania", nativeName: "Arrernte" },
  
  // ==================== SIGN LANGUAGES ====================
  { value: "asl", label: "American Sign Language", region: "Sign Languages", nativeName: "ASL" },
  { value: "bsl", label: "British Sign Language", region: "Sign Languages", nativeName: "BSL" },
  { value: "lsf", label: "French Sign Language", region: "Sign Languages", nativeName: "LSF" },
  { value: "dgs", label: "German Sign Language", region: "Sign Languages", nativeName: "DGS" },
  { value: "auslan", label: "Australian Sign Language", region: "Sign Languages", nativeName: "Auslan" },
  { value: "jsl", label: "Japanese Sign Language", region: "Sign Languages", nativeName: "日本手話" },
  { value: "csl", label: "Chinese Sign Language", region: "Sign Languages", nativeName: "中国手语" },
  { value: "isl", label: "International Sign", region: "Sign Languages", nativeName: "IS" },
]

export const regions = Array.from(new Set(languages.map(l => l.region))).sort()
